name: Create Monthly Time Off Issue
on:
  schedule:
  - cron: "0 0 1 * *"
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: JasonEtco/create-an-issue@v2.0.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/monthly-time-off-issue-template.md
