name: "Hello World"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo Hello, world!
    - run: printenv
    - run: echo $GITHUB_REF
    - run: echo $GITHUB_HEAD_REF
    - run: echo $GITHUB_BASE_REF
    - run: cat $GITHUB_EVENT_PATH
