name: "Hello World"
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo Hello, world!
    - run: printenv
    - run: echo $GITHUB_EVENT_NAME
    - run: echo $GITHUB_REF
    - run: cat $GITHUB_EVENT_PATH
