name: "Commit and push changes to the current repo"
on: push
jobs:
  push-changes:
    runs-on: ubuntu-latest
    steps:
    - name: "Check out the repo"
      uses: actions/checkout@v1
      
    - name: "Work around detached head issue (https://github.com/actions/checkout/issues/6)"
      run: |
        # Use GITHUB_HEAD_REF for pull_request events
        git checkout ${GITHUB_REF#refs/heads/}
      
    - name: "Configure git"
      run: |
        # Set up token auth. Maybe actions/checkout will do this step some day?
        git remote set-url origin https://x-access-token:${{github.token}}@github.com/${{github.repository}}.git

        # Tell git who we are.
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
      
    - name: "Change one or more files"
      run: |
        # Do your thing here. Generate docs, translate your files to pig latin, etc.
        date >> added_by_push-changes.yml.txt
        echo "Event: $GITHUB_EVENT_NAME" >> added_by_push-changes.yml.txt
        # Activity type will be null for push events
        echo "Activity type: `jq '.action' $GITHUB_EVENT_PATH`" >> added_by_push-changes.yml.txt
        echo "Ref: $GITHUB_REF" >> added_by_push-changes.yml.txt
        echo "Sha: $GITHUB_SHA" >> added_by_push-changes.yml.txt 
        echo "Message: `jq '.head_commit.message' $GITHUB_EVENT_PATH`" >> added_by_push-changes.yml.txt
        echo >> added_by_push-changes.yml.txt
        
    - name: "Add, commit and push changes"
      run: |
        git add .
        git commit -m "Various changes"
        git push
